project:
  type: book

book:
  title: "JuliaEpiHandbook"
  subtitle: "A Guide to Julia for Epidemiologists"
  author:
    - name: "Callum Arnold-Leps"
      url: https://callumarnold.com
      affiliation: Pennsylvania State University
      orcid: 0000-0002-3245-6956
  date: "2024-05-31"
  chapters:
    - index.qmd
    - part: "Background"
      chapters:
      - motivations-background.qmd
      - technical-background.qmd
    - part: "Getting Started With Julia"
      chapters:
        - install-julia.qmd
        - julia-basics.qmd
        - new-project.qmd
        - import-export.qmd
    - part: "TODO"
      chapters:
        - todo.qmd
        - misc.qmd
    # - references.qmd
  repo-url: https://github.com/arnold-c/JuliaEpiHandbook
  repo-actions: [edit]
  sidebar:
    search: true
    border: true
  search:
    keyboard-shortcut: ["?", "s"]
  bread-crumbs: true
  google-analytics: "G-EVYBCCRZHE"

bibliography: references.bib

license: "CC BY"

# Default for table of contents
toc: true
toc-title: Table of contents
toc-location: right

# Default knitr options
execute:
  echo: true
  message: true
  warning: true
  cache: false
  freeze: auto

# Default author
author:
  - name: Callum Arnold-Leps
    url: https://callumarnold.com
    affiliation: Pennsylvania State University
    orcid: 0000-0002-3245-6956

# Default fields for citation
citation: true

language:
  search-text-placeholder: "[s|?] Search Contents"

format:
  html:
    theme:
      light: [cosmo, format/_fonts.scss, format/_light.scss]
      dark: [cosmo, format/_fonts.scss, format/_dark.scss]
    code-copy: true
    code-fold: false
    code-overflow: wrap
    grid:
      sidebar-width: 270px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
